const MISSION_FIELDS = [
    'decree_num',
    'name',
    'lname',
    'emp_num',
    'job_title',
    'mission_type',
    'device_type',
    'repair_type',
    'region',
    'location',
    'subject',
    'device_serial',
    'duration',
    'overtime_hours',
    'start_date',
    'end_date',
    'issue_date',
    'is_single',
    'is_group',
    'is_supplied',
    'is_unsupplied',
    'is_issued',
    'is_extended',
    'is_gov',
    'is_plane',
    'is_train',
    'is_agency',
    'is_bus',
    'is_personal',
];

module.exports = { MISSION_FIELDS };
